NewsReleaseSystem/Models/CofeDbContext.cs
using System.Data.Entity;
using NewsReleaseSystem.Models.ModelMapping;

namespace NewsReleaseSystem.Models
{
    public class CofeDbContext : DbContext
    {
        public CofeDbContext()
            : base("name=CofeConnectionString")
        {
            Database.SetInitializer<CofeDbContext>(new CreateDatabaseIfNotExists<CofeDbContext>());

            //Database.SetInitializer<SchoolDBContext>(new DropCreateDatabaseIfModelChanges<SchoolDBContext>());
            //Database.SetInitializer<SchoolDBContext>(new DropCreateDatabaseAlways<SchoolDBContext>());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new UserMap());
            modelBuilder.Configurations.Add(new NewsMap());
            modelBuilder.Configurations.Add(new CommentsMap());
        }

        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}

NewsReleaseSystem/Models/Comments.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace NewsReleaseSystem.Models
{
    public class Comments
    {
        /// <summary>
        /// 对应的新闻ID
        /// </summary>
        public int NewsId { get; set; }

        /// <summary>
        /// 对应的新闻
        /// </summary>
        public virtual News News { get; set; }

        /// <summary>
        /// 评论Id
        /// </summary>
        public int CommentsId { get; set; }

        /// <summary>
        /// 评论正文
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 评论Id
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// 评论 : 评论者 = 1 : 1
        /// </summary>
        public virtual User User { get; set; }

        /// <summary>
        /// 评论时间
        /// </summary>
        [DataType(DataType.DateTime)]
        public DateTime Time { get; set; }
    }
}

NewsReleaseSystem/Models/ModelMapping/CommentsMap.cs
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;

namespace NewsReleaseSystem.Models.ModelMapping
{
    public class CommentsMap : EntityTypeConfiguration<Comments>
    {
        public CommentsMap()
        {
            // Primary Key
            HasKey(c => c.CommentsId);

            // Relationship
            // News : Comments = 1 : *
            HasRequired(c => c.News).WithMany(n => n.Comments).HasForeignKey(c => c.NewsId);
            // User : Comments = 1 : *
            HasRequired(c => c.User).WithMany(u => u.Comments).HasForeignKey(c => c.UserId);

            // Property Constraints
            Property(c => c.CommentsId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(c => c.Content).HasMaxLength(200).IsRequired();

        }
    }
}

NewsReleaseSystem/Models/ModelMapping/NewsMap.cs
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;

namespace NewsReleaseSystem.Models.ModelMapping
{
    public class NewsMap : EntityTypeConfiguration<News>
    {
        public NewsMap()
        {
            // Primary Key
            HasKey(n => n.NewsId);

            // Relationship
            HasMany(n => n.Comments).WithRequired(c => c.News).WillCascadeOnDelete();

            // Property Constraints
            Property(n => n.NewsId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(n => n.Title).IsRequired().HasMaxLength(50);
            Property(n => n.Content).IsUnicode().IsRequired();

            // Table && Column Mapping
            ToTable("News", "dbo");

            // Ignore
            // Ignore(n => n.prop);
        }
    }
}

NewsReleaseSystem/Models/ModelMapping/UserMap.cs
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;

namespace NewsReleaseSystem.Models.ModelMapping
{
    public class UserMap : EntityTypeConfiguration<User>
    {
        public UserMap()
        {
            // Primary Key
            HasKey(u => u.UserId);

            // Relationships
            HasMany(u => u.Comments).WithRequired(c => c.User).WillCascadeOnDelete();

            // Property Constraints
            Property(u => u.UserId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(u => u.Name).IsUnicode().IsRequired().HasMaxLength(20);
            Property(u => u.Password).IsRequired().HasMaxLength(15);
            Property(u => u.Email).IsRequired();

            // Table && Column Mapping
            ToTable("User", "dbo");

            // Ignore
            // Ignore(u => u.prop);
        }
    }
}

NewsReleaseSystem/Models/News.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NewsReleaseSystem.Models
{
    public class News
    {
        /// <summary>
        /// 新闻ID
        /// </summary>
        public int NewsId { get; set; }

        /// <summary>
        /// 新闻标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 新闻正文
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 发布人
        /// </summary>
        public string Publisher { get; set; }

        /// <summary>
        /// 发布时间
        /// </summary>
        [DataType(DataType.DateTime)]
        public DateTime ReleaseTime { get; set; }

        /// <summary>
        /// 新闻图片
        /// </summary>
        public string ImagePath { get; set; }

        /// <summary>
        /// 新闻 : 新闻评论 = 1 : *
        /// </summary>
        public virtual ICollection<Comments> Comments { get; set; }
    }
}

NewsReleaseSystem/Models/User.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NewsReleaseSystem.Models
{
    public class User
    {
        /// <summary>
        /// 用户ID
        /// </summary>
        public int UserId { get; set; }
        
        /// <summary>
        /// 用户名称
        /// </summary>
        [Required(ErrorMessage = "用户名不能为空")]
        [MaxLength(20, ErrorMessage = "用户名不能超过20个字符")]
        public string Name { get; set; }

        /// <summary>
        /// 用户邮箱
        /// </summary>
        [Required(ErrorMessage = "邮箱不能为空")]
        [DataType(DataType.EmailAddress, ErrorMessage = "非法的邮箱,请重试")]
        public string Email { get; set; }

        /// <summary>
        /// 用户密码
        /// </summary>
        [Required(ErrorMessage = "密码不能为空")]
        [MaxLength(15, ErrorMessage = "密码长度不能超过15个字符")]
        public string Password { get; set; }

        /// <summary>
        /// 用户头像路径
        /// </summary>
        public string AvatarPath { get; set; }

        /// <summary>
        /// 用户 : 用户评论 = 1 : *
        /// </summary>
        public ICollection<Comments> Comments { get; set; }
    }
}

NewsReleaseSystem/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsReleaseSystem.Models;
using NewsReleaseSystem.BLL;
using NewsReleaseSystem.BLL.Authentication;

namespace NewsReleaseSystem.Controllers
{
    public class AuthenticationController : Controller
    {
        public ActionResult SignIn()
        {
            return View();
        }

        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignInValidation(User user)
        {
            if (!Authenticator.CheckUserExists(user))
            {
                JsHelper.Alert("用户名或者密码错误,请重试!");
                return View();
            }
            return Redirect("~/Home/Index");
        }

        [HttpPost]
        public void SignUpHandler(User user)
        {
            string msg = "";
            if (!ModelState.IsValid)
            {
                msg = "数据验证失败, 请重试!";
                JsHelper.AlertAndRedirect(msg, "SignUp");
            }
            else
            {
                msg = "数据验证通过";
                //_context.Users.Add(user);
                //_context.SaveChanges();
            }
            return;
        }
    }
}

NewsReleaseSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsReleaseSystem.Controllers
{
    public class HomeController : Controller
    {
        // Get: Home/Index
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NewsReleaseSystem/Views/Authentication/SignIn.cshtml
@{
    Layout = "~/Views/Shared/_AuthenticationPartial.cshtml";
}

<div class="main">
    <!-- Sing in  Form -->
    <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <div class="signin-image">
                    <figure><img src="~/Content/my/authentication/images/signin-image.jpg" alt="sing up image"></figure>
                    @Html.ActionLink("Create an account", "SignUp", "Authentication", null, new { @class = "signup-image-link"})
                </div>
                <div class="signin-form">
                    <h2 class="form-title">Sign In</h2>
                    <form action="~/Authentication/SignInValidation" method="POST" class="register-form" id="login-form">
                        <div class="form-group">
                            <label for="email"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            <input type="text" name="Email" id="email" placeholder="Your Email" />
                        </div>
                        <div class="form-group">
                            <label for="pwd"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="Password" id="pwd" placeholder="Your Password" />
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                            <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="signin" id="signin" class="form-submit" value="Log in" />
                        </div>
                    </form>
                    <div class="social-login">
                        <span class="social-label">Or login with</span>
                        <ul class="socials">
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

NewsReleaseSystem/Views/Authentication/SignUp.cshtml
@model NewsReleaseSystem.Models.User
@{
    Layout = "~/Views/Shared/_AuthenticationPartial.cshtml";
}

<!-- Sign up form -->
@using (Html.BeginForm("SignUpHandler", "Authentication", FormMethod.Post, new { @class = "register-form" }))
{
    @Html.AntiForgeryToken()
    <div class="main">
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <div class="form-group">
                            <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Your Name" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-warning" })
                        </div>

                        <div class="form-group">
                            <label for="email"><i class="zmdi zmdi-email"></i></label>
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Your Email" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-warning" })
                        </div>

                        <div class="form-group">
                            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Password" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-warning" })
                        </div>

                        <div class="form-group">
                            <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                            <input type="password" name="re_pass" id="re_pass" placeholder="Repeat your password" />
                        </div>

                        <div class="form-group">
                            <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                            <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                        </div>

                        <div class="form-group form-button">
                            <input type="submit" name="signup" id="signup" class="form-submit" value="Register" />
                        </div>
                    </div>
                    <div class="signup-image">
                        <figure><img src="~/Content/my/authentication/images/signup-image.jpg" alt="sing up image"></figure>
                        @Html.ActionLink("I am already member", "SignIn", "Authentication", null, new { @class = "signup-image-link" })
                    </div>
                </div>
            </div>
        </section>
    </div>
}

<script>
    $(".validation-summary-errors").removeClass("validation-summary-errors");
    $(".input-validation-error").removeClass("input-validation-error").parent().addClass("has-error");
</script>

NewsReleaseSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NewsReleaseSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NewsReleaseSystem/Views/Home/Index.cshtml
<!-- Page Content -->
<div class="container">
    <h1 class="my-4">Welcome to Modern Business</h1>
    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <h4 class="card-header">Card Title</h4>
                <div class="card-body">
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary">Learn More</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <h4 class="card-header">Card Title</h4>
                <div class="card-body">
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis ipsam eos, nam perspiciatis natus commodi similique totam consectetur praesentium molestiae atque exercitationem ut consequuntur, sed eveniet, magni nostrum sint fuga.</p>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary">Learn More</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <h4 class="card-header">Card Title</h4>
                <div class="card-body">
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary">Learn More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <!-- Portfolio Section -->
    <h2>Portfolio Heading</h2>

    <div class="row">
        <div class="col-lg-4 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Project One</a>
                    </h4>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Project Two</a>
                    </h4>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Project Three</a>
                    </h4>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quisquam, error quod sed cumque, odio distinctio velit nostrum temporibus necessitatibus et facere atque iure perspiciatis mollitia recusandae vero vel quam!</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Project Four</a>
                    </h4>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Project Five</a>
                    </h4>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Project Six</a>
                    </h4>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->

    <!-- Features Section -->
    <div class="row">
        <div class="col-lg-6">
            <h2>Modern Business Features</h2>
            <p>The Modern Business template by Start Bootstrap includes:</p>
            <ul>
                <li>
                    <strong>Bootstrap v4</strong>
                </li>
                <li>jQuery</li>
                <li>Font Awesome</li>
                <li>Working contact form with validation</li>
                <li>Unstyled page elements for easy customization</li>
            </ul>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
        </div>
        <div class="col-lg-6">
            <img class="img-fluid rounded" src="http://placehold.it/700x450" alt="">
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Call to Action Section -->
    <div class="row mb-4">
        <div class="col-md-8">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
        </div>
        <div class="col-md-4">
            <a class="btn btn-lg btn-secondary btn-block" href="#">Call to Action</a>
        </div>
    </div>

</div>
<!-- /.container -->

NewsReleaseSystem/Views/Shared/_AuthenticationPartial.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Authentication</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="~/Content/my/authentication/fonts/material-icon/css/material-design-iconic-font.min.css" />
    <!-- Main css -->
    <link rel="stylesheet" href="~/Content/my/authentication/css/style.css" />
</head>

<body>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

NewsReleaseSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - News Release System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/Home/Index">新闻发布系统</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="services.html">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Contact</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Portfolio
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                            <a class="dropdown-item" href="portfolio-1-col.html">1 Column Portfolio</a>
                            <a class="dropdown-item" href="portfolio-2-col.html">2 Column Portfolio</a>
                            <a class="dropdown-item" href="portfolio-3-col.html">3 Column Portfolio</a>
                            <a class="dropdown-item" href="portfolio-4-col.html">4 Column Portfolio</a>
                            <a class="dropdown-item" href="portfolio-item.html">Single Portfolio Item</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Blog
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                            <a class="dropdown-item" href="blog-home-1.html">Blog Home 1</a>
                            <a class="dropdown-item" href="blog-home-2.html">Blog Home 2</a>
                            <a class="dropdown-item" href="blog-post.html">Blog Post</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Other Pages
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                            <a class="dropdown-item" href="full-width.html">Full Width Page</a>
                            <a class="dropdown-item" href="sidebar.html">Sidebar Page</a>
                            <a class="dropdown-item" href="faq.html">FAQ</a>
                            <a class="dropdown-item" href="404.html">404</a>
                            <a class="dropdown-item" href="pricing.html">Pricing Table</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody();

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
        </div>
        <!-- /.container -->
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>